version: "3.8"

services:
  mongodb-test:
    container_name: mongodb-test
    restart: unless-stopped
    logging:
      driver: none
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  backend_test:
    depends_on:
      - mongodb-test
    container_name: node-app-test
    restart: "no"
    build:
      context: ./server
      dockerfile: Dockerfile.test
    tty: true
    volumes:
      - ./server:/backend-app
    environment:
      - SECRET_KEY=$APP_SECRET
      - DB_HOST=mongodb-test
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - PORT=$NODE_DOCKER_PORT
      - PROXY_PORT=$NGINX_LOCAL_PORT
      - GAPP_CLIENT_ID=$GAPP_CLIENT_ID
      - GAPP_CLIENT_SECRET=$GAPP_CLIENT_SECRET
      - GITPOD_WORKSPACE_URL=$GITPOD_WORKSPACE_URL
      - IS_DOCKER=true
